# TLS code signing certificate request

[ req ]
default_bits				= 4096							# RSA key size
encrypt_key				= no							# Protect private key
default_md				= sha512						# MD to use
utf8					= yes							# Input is UTF-8
string_mask				= utf8only						# Emit UTF-8 strings
prompt					= yes							# Prompt for DN
distinguished_name			= server_dn						# DN template
req_extensions				= server_reqext						# Desired extensions

[ server_dn ]
countryName				= "Enter a country (2 letters)"
countryName_default			= "US"
countryName_max				= 2
stateOrProvinceName			= "Enter a state (Name)"
stateOrProvinceName_default		= "New York"
stateOrProvinceName_max			= 32
localityName				= "Enter a city"
localityName_default			= "New York"
localityName_max			= 32
organizationName			= "Enter an organization"
organizationName_default		= "Example"
organizationName_max			= 64
organizationalUnitName			= "Enter an organizational unit"
organizationalUnitName_default		= "Development"
organizationalUnitName_max		= 64
emailAddress				= "Enter an email address"
emailAddress_default			= "contact@example.com"
emailAddress_max			= 64
commonName				= "Enter a common name"
commonName_default			= "Example Code Signing"
commonName_max				= 64

[ server_reqext ]
keyUsage				= critical,digitalSignature
extendedKeyUsage			= codeSigning
subjectKeyIdentifier			= hash
